---
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: master
rule_files:
  - "./rules/*/*.rules.yml"
alerting:
  alert_relabel_configs: []
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093
remote_read: []
remote_write: []
